channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - nodejs
 - pandas
 - dask>=2022.12
 - distributed 
 - jupyter
 - jupyterlab
 - jupyter-server-proxy
 - jupytext
 - dask-labextension
 - tensorflow>=2.11
 - keras
 - tensorboard
 - scikit-learn
 - statsmodels
 - matplotlib
 - cartopy
 - geopandas
 - shapely
 - netCDF4
 - scipy
 - h5netcdf
 - cftime
 - xarray
 - cf_xarray=0.7.4
 - rioxarray
 - nc-time-axis>=1.2.0
 - xesmf
 - seaborn
 - keras-tuner
 - pip
 - pip: 
   - tensorboard_plugin_profile
   - pydot
